"""add pin

Revision ID: 5a761196152c
Revises: b0962d8ee6f0
Create Date: 2025-04-21 12:34:45.613159

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5a761196152c"
down_revision = "b0962d8ee6f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events_attendees", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pin", sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events_attendees", schema=None) as batch_op:
        batch_op.drop_column("pin")

    # ### end Alembic commands ###
