"""remove ends_at column from event

Revision ID: b0962d8ee6f0
Revises: d5a696fbc3d6
Create Date: 2025-04-16 17:26:12.171157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0962d8ee6f0'
down_revision = 'd5a696fbc3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('ends_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ends_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
