"""add yes or no for male and female for each speed date

Revision ID: e77c1435e6f0
Revises: 8623f986afc0
Create Date: 2025-03-25 13:56:52.024867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77c1435e6f0'
down_revision = '8623f986afc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_speed_dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('male_interested', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('female_interested', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_speed_dates', schema=None) as batch_op:
        batch_op.drop_column('female_interested')
        batch_op.drop_column('male_interested')

    # ### end Alembic commands ###
