"""remove ends at

Revision ID: f6e98c6ae2ac
Revises: make_ends_at_nullable
Create Date: 2025-04-22 09:18:48.370103

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f6e98c6ae2ac"
down_revision = "make_ends_at_nullable"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("ends_at")

    with op.batch_alter_table("events_attendees", schema=None) as batch_op:
        batch_op.drop_column("pin")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events_attendees", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("pin", sa.VARCHAR(length=4), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ends_at",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
