name: Deploy sas-api

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: deploy_prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          script: |
            set -e
            cd /home/ubuntu/SAS/sas-api
            pwd
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            source /home/ubuntu/SAS/sas-api/venv/bin/activate
            pip install -r requirements.txt
            black . || echo "Black formatting completed with warnings"
            if git diff --name-only | grep -qE '^(app|scripts|tests)'; then
              git add .
              git config --global user.email "github-actions@github.com"
              git config --global user.name "GitHub Actions"
              git commit -m "Updating code formatting for deployment" || echo "No changes to commit"
              git push origin ${{ github.ref_name }} || echo "No changes to push"
            else
              echo "No changes detected in app, scripts, or tests directories"
            fi
            sudo systemctl restart SAS.service 