name: Deploy sas-api

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: deploy_prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          script: |
            set -e
            cd /home/ubuntu/SAS/sas-api
            pwd
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            source /home/ubuntu/SAS/sas-api/venv/bin/activate
            pip install -r requirements.txt
            black . || true
            if git diff --name-only HEAD~1 HEAD | grep -qE '^(app|scripts|tests)'; then
              git add .
              git commit -m "Updating code formatting for deployment"
              git push origin ${{ github.ref_name }}
            fi           
            sudo systemctl restart SAS.service 